In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf
from bs4 import BeautifulSoup
from datetime import datetime as dt
import urllib3
# import re2
import regex
import re
import io
from requests.exceptions import HTTPError
from IPython.core.display import HTML
import requests
import datetime    
from pandas.tseries.offsets import BDay    # BDay is business day, not birthday 
from pandas.tseries.holiday import USFederalHolidayCalendar
from pandas.tseries.offsets import CustomBusinessDay
from numpy import busday_offset

In [2]:
US_BUSINESS_DAY = CustomBusinessDay(calendar=USFederalHolidayCalendar())

In [3]:
Tickers_EarningsCallsDates = pd.read_csv("../data/Descending_Ticker_Industry.csv")
Tickers_EarningsCallsDates

/var/folders/nl/hqcw9pqd0ns4q0b61syv0q2m0000gn/T/ipykernel_9615/1723752497.py:1: DtypeWarning: Columns (39) have mixed types. Specify dtype option on import or set low_memory=False.
  Tickers_EarningsCallsDates = pd.read_csv("../data/Descending_Ticker_Industry.csv")

,gvkey,date,PRisk,NPRisk,Risk,PSentiment,NPSentiment,Sentiment,PRiskT_economic,PRiskT_environment,...,Ebola_Exposure,Brexit_Exposure,Brexit_Neg_Sentiment,Brexit_Pos_Sentiment,Brexit_Net_Sentiment,Brexit_Risk,Min_Net_COVID_Sentiment,Max_Net_COVID_Sentiment,Delta_Net_COVID_Sentiment,Industry
0,14477,241,432.132417,3003.168794,155.436913,-272.501712,12011.321451,223.018179,10793.205216,7326.087222,...,0.0,NaN,NaN,NaN,NaN,NaN,-0.594354,0.343672,0.938026,Waste Management
1,14477,242,83.353677,418.241153,56.901317,2381.304228,15431.417730,942.936108,6140.950967,2632.132850,...,0.0,NaN,NaN,NaN,NaN,NaN,-0.594354,0.343672,0.938026,Waste Management
2,14477,243,172.261300,544.684961,74.041167,1731.590225,15776.732640,792.240486,5580.077306,5162.947754,...,0.0,NaN,NaN,NaN,NaN,NaN,-0.594354,0.343672,0.938026,Waste Management
3,14477,244,139.561598,2046.072722,38.562394,2627.900226,14265.187510,1126.021903,3113.977050,4799.040713,...,0.0,NaN,NaN,NaN,NaN,NaN,-0.594354,0.343672,0.938026,Waste Management
4,14477,245,43.279339,49.137675,15.395274,351.918863,27569.330045,1508.736818,220.079331,668.532514,...,0.0,NaN,NaN,NaN,NaN,NaN,-0.594354,0.343672,0.938026,Waste Management
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16435,25848,241,1091.949502,1730.933490,180.683311,-1343.333986,-9629.830966,-164.257556,22680.948925,19217.822176,...,0.0,NaN,NaN,NaN,NaN,NaN,-1.050604,-1.050604,0.000000,NaN
16436,34441,246,109.714299,4062.912176,235.710077,1770.733612,-20276.647117,294.637596,9423.366401,5196.877825,...,0.0,NaN,NaN,NaN,NaN,NaN,-1.279591,-1.279591,0.000000,NaN
16437,64480,241,68.992400,2583.291393,71.479628,804.640737,4637.667920,929.235168,2362.023126,1714.658665,...,0.0,NaN,NaN,NaN,NaN,NaN,0.373552,0.373552,0.000000,NaN
16438,175110,241,171.400467,3724.226056,107.449857,-151.265131,-1795.438398,107.449857,6532.694413,6873.944619,...,0.0,NaN,NaN,NaN,NaN,NaN,-1.238646,-1.238646,0.000000,NaN
16439,187128,243,238.402735,950.353326,67.024129,1478.256340,27023.699768,1447.721180,2514.587382,4530.682929,...,0.0,NaN,NaN,NaN,NaN,NaN,0.296780,0.296780,0.000000,NaN

In [4]:
# Tickers_EarningsCallsDates = Tickers_EarningsCallsDates.sort_values(by=['date_earningscall', 'ticker'], ascending=False, na_position='last')

In [5]:
Tickers_EarningsCallsDates['date_earningscall'] = pd.to_datetime(Tickers_EarningsCallsDates['date_earningscall'], unit='ns')

In [6]:
# Test_Day = datetime.datetime.today()
# FourBusinessDaysAgo = Test_Day - BDay(4)
# FourBusinessDaysAgo

In [7]:
Tickers_EarningsCallsDates['DayBefore_EarningsCall'] = Tickers_EarningsCallsDates['date_earningscall'] - 1*US_BUSINESS_DAY
# Tickers_EarningsCallsDates['ClosingPrice_DayBefore_EarningsCall'] = ""
Tickers_EarningsCallsDates['DateOf_EarningsCall'] = Tickers_EarningsCallsDates['date_earningscall'] 
# Tickers_EarningsCallsDates['ClosingPrice_DayOf_EarningsCall'] = ""
Tickers_EarningsCallsDates['DayAfter_EarningsCall'] = Tickers_EarningsCallsDates['date_earningscall'] + 1*US_BUSINESS_DAY 
# Tickers_EarningsCallsDates['ClosingPrice_DayAfter_EarningsCall'] = ""
# Tickers_EarningsCallsDates['PercentChange_bt_ClosingPrices_DayBefore_y_DayAfter'] = ""

/var/folders/nl/hqcw9pqd0ns4q0b61syv0q2m0000gn/T/ipykernel_9615/2614812069.py:1: PerformanceWarning: Non-vectorized DateOffset being applied to Series or DatetimeIndex.
  Tickers_EarningsCallsDates['DayBefore_EarningsCall'] = Tickers_EarningsCallsDates['date_earningscall'] - 1*US_BUSINESS_DAY
/var/folders/nl/hqcw9pqd0ns4q0b61syv0q2m0000gn/T/ipykernel_9615/2614812069.py:5: PerformanceWarning: Non-vectorized DateOffset being applied to Series or DatetimeIndex.
  Tickers_EarningsCallsDates['DayAfter_EarningsCall'] = Tickers_EarningsCallsDates['date_earningscall'] + 1*US_BUSINESS_DAY

In [8]:
Tickers_EarningsCallsDates['ticker']=Tickers_EarningsCallsDates['ticker'].astype('str')
Tickers_EarningsCallsDates['date_earningscall']=Tickers_EarningsCallsDates['date_earningscall'].astype('str')
Tickers_EarningsCallsDates['DayBefore_EarningsCall']=Tickers_EarningsCallsDates['DayBefore_EarningsCall'].astype('str')
Tickers_EarningsCallsDates['DayAfter_EarningsCall']=Tickers_EarningsCallsDates['DayAfter_EarningsCall'].astype('str')

In [9]:
Tickers_EarningsCallsDates

,gvkey,date,PRisk,NPRisk,Risk,PSentiment,NPSentiment,Sentiment,PRiskT_economic,PRiskT_environment,...,Brexit_Pos_Sentiment,Brexit_Net_Sentiment,Brexit_Risk,Min_Net_COVID_Sentiment,Max_Net_COVID_Sentiment,Delta_Net_COVID_Sentiment,Industry,DayBefore_EarningsCall,DateOf_EarningsCall,DayAfter_EarningsCall
0,14477,241,432.132417,3003.168794,155.436913,-272.501712,12011.321451,223.018179,10793.205216,7326.087222,...,NaN,NaN,NaN,-0.594354,0.343672,0.938026,Waste Management,2020-05-05,2020-05-06,2020-05-07
1,14477,242,83.353677,418.241153,56.901317,2381.304228,15431.417730,942.936108,6140.950967,2632.132850,...,NaN,NaN,NaN,-0.594354,0.343672,0.938026,Waste Management,2020-07-29,2020-07-30,2020-07-31
2,14477,243,172.261300,544.684961,74.041167,1731.590225,15776.732640,792.240486,5580.077306,5162.947754,...,NaN,NaN,NaN,-0.594354,0.343672,0.938026,Waste Management,2020-10-30,2020-11-02,2020-11-03
3,14477,244,139.561598,2046.072722,38.562394,2627.900226,14265.187510,1126.021903,3113.977050,4799.040713,...,NaN,NaN,NaN,-0.594354,0.343672,0.938026,Waste Management,2021-02-17,2021-02-18,2021-02-19
4,14477,245,43.279339,49.137675,15.395274,351.918863,27569.330045,1508.736818,220.079331,668.532514,...,NaN,NaN,NaN,-0.594354,0.343672,0.938026,Waste Management,2021-04-26,2021-04-27,2021-04-28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16435,25848,241,1091.949502,1730.933490,180.683311,-1343.333986,-9629.830966,-164.257556,22680.948925,19217.822176,...,NaN,NaN,NaN,-1.050604,-1.050604,0.000000,NaN,2020-05-13,2020-05-14,2020-05-15
16436,34441,246,109.714299,4062.912176,235.710077,1770.733612,-20276.647117,294.637596,9423.366401,5196.877825,...,NaN,NaN,NaN,-1.279591,-1.279591,0.000000,NaN,2021-08-09,2021-08-10,2021-08-11
16437,64480,241,68.992400,2583.291393,71.479628,804.640737,4637.667920,929.235168,2362.023126,1714.658665,...,NaN,NaN,NaN,0.373552,0.373552,0.000000,NaN,2020-05-05,2020-05-06,2020-05-07
16438,175110,241,171.400467,3724.226056,107.449857,-151.265131,-1795.438398,107.449857,6532.694413,6873.944619,...,NaN,NaN,NaN,-1.238646,-1.238646,0.000000,NaN,2020-05-12,2020-05-13,2020-05-14
16439,187128,243,238.402735,950.353326,67.024129,1478.256340,27023.699768,1447.721180,2514.587382,4530.682929,...,NaN,NaN,NaN,0.296780,0.296780,0.000000,NaN,2020-11-02,2020-11-03,2020-11-04

In [10]:
Tickers_EarningsCallsDates.to_csv("../data/AdjacentBusinessDays_TickersEarningsCallsSheet.csv", index=False)